### ISSUE TITLE
Use a more traditional Object-Oriented approach

### ISSUE THREAD

**Issue by ghost** [oTranscribe/oT2#1]
Hi Elliot,

I just had a quick look at the code and I noticed that the Player for instance, is used like a traditional class, but not written like one. ( i.e. you'd write `var p = Player()` instead of `var p = new Player()` ).

I was wondering how you felt about moving to a more traditional approach ? 
If it sounds good to you then I would be happy to convert the existing classes in this repo :)

Have a good day,
Alvin

**Comment by ejb** [comment]
Hi Alvin, thanks for taking a look through the code! Yeah, in retrospect it'd probably be easier for others to make sense of the code if it was a regular prototypical class. If you have time to rewrite it, that'd be awesome!
